<style>
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap");
    * {
    padding: 0;
    margin: 0;
    }

    body {
    display: grid;
    place-items: center;
    height: 100vh;
    font-family: "Poppins", sans-serif;
    background-image: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
    background-size: 400% 400%;
    animation: gradient 30s ease infinite;
    position: relative;
    }

    @keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
    50% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
    }
    .container {
    display: grid;
    grid-template-columns: 1fr 1fr;
    place-items: center;
    padding-block: 5vh;
    gap: 0.57rem;
    }
    .container .avatar {
    grid-column: span 2;
    display: flex;
    justify-content: center;
    width: 250px;
    }
    .container .avatar img {
    width: 175px;
    aspect-ratio: 1;
    border-radius: 50%;
    object-fit: cover;
    }
    .container .username {
    grid-column: span 2;
    margin-block-start: 0.75rem;
    margin-block-end: 2rem;
    color: #fff;
    }
    .container .username h3 {
    text-align: center;
    }
    .container .button {
    width: 120px;
    background-color: transparent;
    color: #fff;
    border: 1.5px solid #fff;
    display: flex;
    justify-content: flex-start;
    align-items: center;
    gap: 0.5rem;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
    transition: color 0.3s, background-color 0.8s;
    }
    .container .button:hover {
    color: #1d1e22;
    background-color: #fff;
    }

    .page {
    position: fixed;
    inset: 0;
    overflow-y: auto;
    transform: scale(0);
    transition: transform 0.3s;
    background-color: #eff2f5;
    color: #1d1e22;
    }
    .page__header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem 5vw;
    background-color: #fff;
    font-weight: bold;
    box-shadow: 0px 5px 5px 0px #e5e5e5;
    }
    .page__title {
    font-size: 1.5rem;
    }
    .page__close {
    display: flex;
    cursor: pointer;
    }
    .page__body {
    padding: 2rem 5vw;
    overflow-y: auto;
    }
    .page--active {
    transform: scale(1);
    }

    h4 {
    margin-block: 10px;
    }

    p {
    margin-block: 15px;
    }

</style>

<?php $this->partial('layouts/header'); ?>


<?php 
    $users = Users::find(
        [
            "id = '". $user_id ."'",
        ]
    ); 
    foreach ($users as $user) {
        break;
    }
?>

<div class='container'>
  <div class='avatar'>
    <img src='https://previews.123rf.com/images/djvstock/djvstock1508/djvstock150806893/44095667-web-developer-design-vector-illustration-eps-10-.jpg?format=auto&amp;version=1638034680&amp;width=300&amp;height=300'>
  </div>
  <div class='username'>
        <?php $name = $user->name; ?>
        <h3><?php echo $name ?? 'Developer Name' ?></h3>
  </div>
  <div class='button' data-target='#home'>
    <div class='button__icon'>
      <i class='fa-solid fa-house'></i>
    </div>
    <div class='button__text'>
      Home
    </div>
  </div>
  <div class='button' data-target='#contact'>
    <div class='button__icon'>
      <i class='fa-solid fa-phone'></i>
    </div>
    <div class='button__text'>
      Contact
    </div>
  </div>
  <div class='button' data-target='#about'>
    <div class='button__icon'>
      <i class='fa-solid fa-user'></i>
    </div>
    <div class='button__text'>
      About
    </div>
  </div>
  <div class='button' data-target='#education'>
    <div class='button__icon'>
      <i class='fa-solid fa-user-graduate'></i>
    </div>
    <div class='button__text'>
      Education
    </div>
  </div>
</div>
<div class='page' id='home'>
  <div class='page__header'>
    <div class='page__title'>
      Home
    </div>
    <div class='page__close'>
      <i class='fa-solid fa-xmark'></i>
    </div>
  </div>
  <div class='page__body'>
    <h4>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</h4>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos optio laboriosam, saepe nulla laborum aperiam nemo sed iure beatae error labore! Mollitia, aperiam adipisci sapiente aliquid non dignissimos enim commodi?</p>
  </div>
</div>
<div class='page' id='contact'>
  <div class='page__header'>
    <div class='page__title'>
      Contact
    </div>
    <div class='page__close'>
      <i class='fa-solid fa-xmark'></i>
    </div>
  </div>
  <div class='page__body'>
    <?php $email = $user->email; ?>
    <h4>Email id : <?php echo $email ?? '' ?></h4>
   </div>
</div>
<div class='page' id='about'>
  <div class='page__header'>
    <div class='page__title'>
      About
    </div>
    <div class='page__close'>
      <i class='fa-solid fa-xmark'></i>
    </div>
  </div>
  <div class='page__body'>
    <h4>Lorem ipsum dolor sit amet consectetur adipisicing.</h4>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos optio laboriosam, saepe nulla laborum aperiam nemo sed iure beatae error labore! Mollitia, aperiam adipisci sapiente aliquid non dignissimos enim commodi?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque fuga molestiae, nihil iste debitis nemo laborum aut aliquid! Quod veritatis dolorem suscipit? Maxime tempore inventore molestias eligendi animi quo at provident vitae nobis, distinctio, molestiae quis accusamus accusantium ullam officia quaerat illo iste! Pariatur provident odit iusto ipsum, natus tenetur alias asperiores temporibus tempora eaque maxime, consectetur similique quasi totam perspiciatis. Architecto dolores facilis quo itaque amet dolore deleniti debitis ab nesciunt doloremque facere nemo sapiente velit expedita consequuntur blanditiis, officia deserunt aperiam sit explicabo numquam omnis. Quod ut unde alias odio, excepturi, deserunt reprehenderit ipsa at, incidunt cumque ipsam consequuntur est! Ipsam itaque unde cupiditate dolorem exercitationem beatae? Eum voluptas ipsam sunt cumque repellendus aperiam sequi reiciendis eos quaerat.</p>
  </div>
</div>
<div class='page' id='education'>
  <div class='page__header'>
    <div class='page__title'>
      Education
    </div>
    <div class='page__close'>
      <i class='fa-solid fa-xmark'></i>
    </div>
  </div>
  <div class='page__body'>
    <h4>Lorem ipsum dolor sit amet consectetur.</h4>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos optio laboriosam, saepe nulla laborum aperiam nemo sed iure beatae error labore! Mollitia, aperiam adipisci sapiente aliquid non dignissimos enim commodi?</p>
    <h4>Lorem ipsum dolor sit.</h4>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eos optio laboriosam, saepe nulla laborum aperiam nemo sed iure beatae error labore! Mollitia, aperiam adipisci sapiente aliquid non dignissimos enim commodi?</p>
    <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam dolorum officia quasi!</h4>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi eius velit animi blanditiis? Suscipit voluptatibus aliquam quasi eveniet facilis laudantium dolor corporis accusamus sint et possimus odio esse iste numquam magnam, veniam, nulla voluptates, architecto molestiae debitis rem consequatur ut earum porro? Incidunt necessitatibus esse aperiam cumque architecto molestiae modi.</p>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(".button").on("click", function () {
        $($(this).data("target")).addClass("page--active");
    });

    $(".page__header").on("click", function () {
        $(".page").removeClass("page--active");
    });

</script>