
<style>

    @import url('https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap');

    * {
        margin: 0;
        padding: 0;
        font-family: 'Poppins', sans-serif;
        user-select: none;
        box-sizing: border-box;
    }

    section {
        position: relative;
        width: 100%;
        height: 100vh;
        background: white;
        display: flex;
        justify-content: center;
        align-items: center;
        overflow: hidden;
    }

    section h2 {
        position: relative;
        font-size: 100px;
        text-align: center;
        line-height: 0.75em;
        text-transform: uppercase;
        font-weight: 800;
    }

    section h2 span {
        font-size: 90px;
        color: transparent;
        -webkit-text-stroke: 0.3vw #000;
    }

    section .black {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: white;
        mix-blend-mode: difference;
    }

</style>
<html lang="en">

<body>

    <?php $this->partial('layouts/header'); ?>

    <section>
        <h2>Welcome to<br><br><span><?php echo $appName; ?></span></h2>
        <div class="black"></div>
    </section>
</body>
</html>
<?php
use Phalcon\Db;
use Phalcon\Db\Exception;
use Phalcon\Db\Adapter\Pdo\Mysql;

$args = [
    'host'      =>  $dbKeys->get( 'host' ),
    'username'  =>  $dbKeys->get( 'username' ),
    'password'  =>  $dbKeys->get( 'password' ),
    'dbname'    =>  $dbKeys->get( 'dbname' ),
];

$connection = new Mysql( $args );

echo '<pre>'; print_r( $connection ); echo '</pre>'; die;
